apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: sayand2002/cart-service  
        ports:
        - containerPort: 2000
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq-service" 
        - name: RABBITMQ_PORT
          value: "5672" 
        - name: MONGODB_URL
          value: "mongodb+srv://sayandak2002:yz7kDhqLsi2cKKDB@cluster0.dlxr05a.mongodb.net/CartService"  
        - name: KAFKA_BROKERS
          value: "kafka-service:9093"  
        - name: KAFKA_TOPIC
          value: "test_topic" 
          
---

apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  type: NodePort 
  selector:
    app: cart-service  
  ports:
    - protocol: TCP
      port: 2000
      targetPort: 2000  
      nodePort: 31101 

