apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service-container
          image: sayand2002/auth-service 
          ports:
            - containerPort: 4040 
          envFrom:
            - configMapRef:
                name: auth-service-config

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-nodeport
spec:
  type: NodePort 
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 4040  
      targetPort: 4040 
      nodePort: 32000
